### ISSUE TITLE
Error in acts_as_heir.rb

### ISSUE THREAD

**Issue by petehamilton** [dipth/Heritage#1]
NameError: uninitialized constant Heritage::ActiveRecord::ActsAsHeir::Post

**Comment by jmsunseri** [comment]
I've got this same issue.

**Comment by dipth** [comment]
Can you provide a trace?

**Comment by raklet** [comment]
It comes from line 18 of acts_as_heir

self._predecessor_klass.columns.reject{|c| c.primary || c.name == Post.inheritance_column || c.name =~ /^heir_/}.map(&:name).each do |att|

"Post.inheritance_....." which doesn't exist unless you are using the heritage demo app.  Remove the second OR condition and the error goes away.
