### ISSUE TITLE
problem accessing parent attributes

### ISSUE THREAD

**Issue by cranieri** [dipth/Heritage#10]
Just downloaded the gem and made some test on the console.
I get an error when I try to get values of attributes of the parent table (posts). 
I launch the following command: @posts = BlogPost.where("posts.title = 'test'") and here is the error message I get:

ERROR:  missing FROM-clause entry for table "posts"
LINE 1: SELECT "blog_posts".\* FROM "blog_posts"  WHERE (posts.title ...

Is that a known issue?

**Comment by ghost** [comment]
I guess that is because he forgot tom implement the magic for that. I have the same issue.

**Comment by dipth** [comment]
The readme has been updated to reflect this.

The way to do it, is to do a join:

``` ruby
@posts = BlogPost.joins(:predecessor).where("posts.title = 'test'")
```
