### ISSUE TITLE
Cyclic update

### ISSUE THREAD

**Issue by greyblake** [dipth/Heritage#2]
It's a perfomance issue.
It sends cyclic update request on model update,
I have Product model as a predecessor and Movie as a heir.
When I update movie it sends 4 request to DB instead of 2.
Here is a simple example to reproduce:

```
mov.name = 'a_new_name'
mov.save
(0.2ms)  UPDATE "products" SET "name" = 'one', "updated_at" = '2011-09-01 14:17:55.933125' WHERE "products"."id" = 2
SQL (0.1ms)  UPDATE "movies" SET "updated_at" = '2011-09-01 14:17:55.934588' WHERE "movies"."id" = 2
SQL (0.0ms)  UPDATE "products" SET "updated_at" = '2011-09-01 14:17:55.935150' WHERE "products"."id" = 2
SQL (0.0ms)  UPDATE "movies" SET "updated_at" = '2011-09-01 14:17:55.935528' WHERE "movies"."id" = 2
```

Environment:
DB: SQLIte3
Rails: 3.1

**Comment by warmwaffles** [comment]
I too get this, but it's only modifying the updated column. Maybe a solution would be to update the :heir's updated_at before updating the predecessor's updated_at field.
